### ISSUE TITLE
Multiple accounts support?

### ISSUE THREAD

**Issue by epinault** [jeffweiss/forcex#20]
so as part of the setup, it is compiling and generating some files to map Sobject from a specific account  from what I can understand.  How would I deal with multiple account that have different object setup ? Does Forcex support that ?

I am evaluating it and this would be a major issue for me to use it if I cannot use multiple account with different object definition in Salesforce

**Comment by jeffweiss** [comment]
Hey @epinault, the mix task that compiles Elixir modules for SObjects isn’t *strictly* required. You could have multiple Config structs for each of the credentials and the specify the SObject along with the Config to some of the more general functions in the Forcex module. I understand this doesn’t provide the IEx / Edoc help for what’s available in each SObject. 
Alternatively you might be able to change the configuration between runs of the mix task to end up with a full set of SObject modules.
If you want to take a stab at a PR for passing config info in via mix task command line, I’ll take a look at it.
