### ISSUE TITLE
Still active and a println

### ISSUE THREAD

**Issue by baldmountain** [jeffweiss/forcex#22]
Hi Jeff,

Just checking to see if this project is being maintained. (We had an issue in the past where a library that we were critically dependent on got renamed and changed into something completely different. So now I am paranoid. :) )

Also, there is an `IO.inspect` here: https://github.com/jeffweiss/forcex/blob/master/lib/forcex/client.ex#L63 that seems to just be a debugging println. If the output is desired, maybe it should be a Logger.debug?

Sorry if I am being a pain,

--
geoff

**Comment by jeffweiss** [comment]
@baldmountain I have changed positions where I no longer interact w/ SFDC on a daily basis and thus don't have quite the same imperative for self-directed updates as before. That said, I will continue to merge pull requests.

**Comment by baldmountain** [comment]
I understand completely. I have a project or two like that too. I'll close this issue since it was more of a "Hi, how are you" kind of request.

Thanks for getting back to me. 

--
geoff
