### ISSUE TITLE
non-empty body causes 'get' calls to fail

### ISSUE THREAD

**Issue by craiglyons** [jeffweiss/forcex#33]
Any `get` call, including `locate_services`, sends a non-empty body, which SF's stock rest api responds to with a generic error.
When I instead send an empty body (i.e. `""`) with the same call, I get the successful response I expect.

The non-empty body is a result of this line's default body of ""
https://github.com/jeffweiss/forcex/blob/master/lib/forcex.ex#L37
being `Poison.encode!`'ed by this line:
https://github.com/jeffweiss/forcex/blob/master/lib/forcex.ex#L16
which results in a body of `"\"\""`.

I'm happy to put up a PR to fix it, but I'm curious if I'm missing something since I would expect this to cause problems for others.

**Comment by jeffweiss** [comment]
Thanks for the report @craiglyons! I have changed employers and no longer have an SFDC. I’ll ask @mmrobins if he can validate.

**Comment by craiglyons** [comment]
@mmrobins `Forcex.Client.login` succeeds, it's the `get` in `Forcex#services` that fails.
It's an html error response indicating "We are down for maintenance." with a 411 code. 
I presume they use 411 (content length required) since a body is present, but the header wouldn't be with a `get`.

Are you testing with a production instance? I'm testing against a sandbox account, which may have tighter restrictions.
