### ISSUE TITLE
Typespec issues

### ISSUE THREAD

**Issue by craiglyons** [jeffweiss/forcex#35]
My application is experiencing dialyzer typespec errors as result of a call to Forcex queries.
Specifically, Forcex query code seems to cause its containing function to report `has no local return` dialyzer messages, which then travels all the way up the stack of my application.

When I run `mix dialyzer` on Forcex, I receive the following list of messages: https://gist.github.com/craiglyons/84846e7e2abe8e757c85673b8a7a13cd#file-forcex-typespec-issues

I see that Forcex does have typespecs; are they currently broken, or is there a problem with a version or way I'm running dialyzer for Forcex?

If it's the former, I may have some time to work on them in a couple weeks.

**Comment by mmrobins** [comment]
dialyzer is now run on CI.  Typespecs could always use some improvements, so feel free to submit them if you have a chance, but going to close this
