### ISSUE TITLE
Login as Dynamic User?

### ISSUE THREAD

**Issue by zolrath** [jeffweiss/forcex#6]
I'm building a service which manages multiple Salesforce accounts and I'd like to be able to create new API clients dynamically, passing in login information retrieved at runtime from a database.

It looks like the only way to pass in login information at the moment is via the config file, limiting forcex to creating clients for a single user?

**Comment by jeffweiss** [comment]
Ah, interesting... I think I should we should be able to make that work with some additions to F.Client.

I'll see what I can come up with later today.

**Comment by jeffweiss** [comment]
@zolrath Thanks for the feedback! This ended up being a pretty straightforward fix, so I pushed it to hex, along with a few other things I'd had in the backlog (like `deflate` support), as 0.4.0. 

You can now supply a map of credentials. Further details in [hexdocs](https://hexdocs.pm/forcex/Forcex.Client.html#login/1).

Please let me know if you have any issues. I'm happy to see this package used. 😃

**Comment by zolrath** [comment]
@jeffweiss Thanks a lot for the fast response time! Nice to see it wasn't an invasive change.
I'll be sure to let you know if I encounter anything, thanks again!
