### ISSUE TITLE
Can we change the endpoint for salesforce?

### ISSUE THREAD

**Issue by tzmfreedom** [jeffweiss/forcex#7]
I want to connect to sandbox or my domain environment with forcex elixir module.
Can I connect to these environments without modifing forcex?
If we have the way to connect, please let me know it.

**Comment by jeffweiss** [comment]
Ah, @tzmfreedom, you're correct. There's no current way to do that. That's clearly a bug. I will see what I can come up with. Thanks for reporting!

**Comment by jeffweiss** [comment]
@tzmfreedom, I've enabled this via `Client.login/2`. Here's an example of how you may use it:

```elixir
client =
  Forcex.Client.default_config
  |> Forcex.Client.login(%Forcex.Client{endpoint: "https://test.salesforce.com"})
  |> Forcex.Client.locate_services
```

**Comment by jeffweiss** [comment]
I should note that I've pushed this to Hex as 0.4.1.

If you have any other problems, please let me know.

Thanks for using forcex! 💜

**Comment by tzmfreedom** [comment]
Great!!
Thank you for your reply and modifing modules!
